version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: confusys_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d confusys_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "
        python wait_for_db.py &&
        echo 'Creating database tables...' &&
        python -c 'from api import create_app, db; app = create_app(); app.app_context().push(); db.create_all()' &&
        echo 'Starting Flask app...' &&
        flask run --host=0.0.0.0 --port=5000
      "
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db:5432/confusys_db
      SECRET_KEY: your-secret-key
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  pgdata: 